### ISSUE TITLE
Database '/path/to/derby/database/dbSNP137' not found.

### ISSUE THREAD

**Issue by YaoXinZhi** [rockt/SETH#28]
I encountered this problem when I ran the script. Please tell me what should I do?

[xzyao@localhost SETH-1.3.1]$ java -cp seth-1.3-Snapshot-jar-with-dependencies.jar de.hu.berlin.wbi.process.Normalize resources/property.xml resources/snpExample.txt
Normalising mutations from 'resources/snpExample.txt' and properties from 'resources/property.xml'
Exception in thread "main" java.lang.IllegalStateException: java.sql.SQLException: Database '/path/to/derby/database/dbSNP137' not found.
	at de.hu.berlin.wbi.objects.DatabaseConnection.connect(DatabaseConnection.java:128)
	at de.hu.berlin.wbi.process.Normalize.main(Normalize.java:65)
Caused by: java.sql.SQLException: Database '/path/to/derby/database/dbSNP137' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at de.hu.berlin.wbi.objects.DatabaseConnection.connect(DatabaseConnection.java:126)
	... 1 more
Caused by: ERROR XJ004: Database '/path/to/derby/database/dbSNP137' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more

**Comment by Erechtheus** [comment]
This error tells you that SETH could not find the local dbSNP  database at the location '/path/to/derby/database/dbSNP137'. The question is, do you need the normalization of mutations?

If yes, follow the instructions under Section "NEN" described here: https://rockt.github.io/SETH/

**Comment by YaoXinZhi** [comment]
Yes, I need to carry out the NEN task, thank you for your answer, I have solved this problem
