### ISSUE TITLE
Unable to run NEN example

### ISSUE THREAD

**Issue by yuanhao96** [rockt/SETH#39]
SETH installed following https://rockt.github.io/SETH/:
git clone https://github.com/rockt/SETH.git
cd SETH
mvn clean compile assembly:single
mv ./target/seth-1.3.2-Snapshot-jar-with-dependencies.jar seth.jar

Works well running NER example:
java -cp seth.jar seth.ner.wrapper.SETHNERAppMut "G-banding and spectral karyotyping showed 46,XX,t(9;11)(p22;p15)."

Error when running NEN example:
java -cp seth.jar de.hu.berlin.wbi.process.Normalize resources/seth_properties.xml resources/snpExample.txt

Normalising mutations from 'resources/snpExample.txt' and properties from 'resources/seth_properties.xml'
Exception in thread "main" java.lang.IllegalStateException: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at de.hu.berlin.wbi.objects.DatabaseConnection.connect(DatabaseConnection.java:111)
	at de.hu.berlin.wbi.process.Normalize.main(Normalize.java:48)
Caused by: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at de.hu.berlin.wbi.objects.DatabaseConnection.connect(DatabaseConnection.java:109)
	... 1 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)

**Comment by Erechtheus** [comment]
Hi! You need to set-up a local dbSNP database before you can normalize mutations. You can either download old dumps of dbSNP or buid a dbSNP database by yourself. See (Rebuilding the database for SNP normalization)
This page should help you (https://github.com/rockt/SETH/blob/gh-pages/index.md).
